/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashRouteImport } from './routes/cash'
import { Route as SwipeRouteImport } from './routes/swipe'
import { Route as ExpensesNewRouteImport } from './routes/expenses/new'
import { Route as ExpensesUploadRouteImport } from './routes/expenses/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const SwipeRoute = SwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesUploadRoute = ExpensesUploadRouteImport.update({
  id: '/expenses/upload',
  path: '/expenses/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/swipe': typeof SwipeRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/upload': typeof ExpensesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/swipe': typeof SwipeRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/upload': typeof ExpensesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash': typeof CashRoute
  '/swipe': typeof SwipeRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/upload': typeof ExpensesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cash' | '/swipe' | '/expenses/new' | '/expenses/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cash' | '/swipe' | '/expenses/new' | '/expenses/upload'
  id:
    '__root__' | '/' | '/cash' | '/swipe' | '/expenses/new' | '/expenses/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashRoute: typeof CashRoute
  SwipeRoute: typeof SwipeRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesUploadRoute: typeof ExpensesUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/upload': {
      id: '/expenses/upload'
      path: '/expenses/upload'
      fullPath: '/expenses/upload'
      preLoaderRoute: typeof ExpensesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashRoute: CashRoute,
  SwipeRoute: SwipeRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesUploadRoute: ExpensesUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
