/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomePeriodRouteImport } from './routes/home/$period'

const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePeriodRoute = HomePeriodRouteImport.update({
  id: '/home/$period',
  path: '/home/$period',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/balance': typeof BalanceRoute
  '/home/$period': typeof HomePeriodRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/balance': typeof BalanceRoute
  '/home/$period': typeof HomePeriodRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/balance': typeof BalanceRoute
  '/home/$period': typeof HomePeriodRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/balance' | '/home/$period' | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/balance' | '/home/$period' | '/home'
  id: '__root__' | '/balance' | '/home/$period' | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BalanceRoute: typeof BalanceRoute
  HomePeriodRoute: typeof HomePeriodRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$period': {
      id: '/home/$period'
      path: '/home/$period'
      fullPath: '/home/$period'
      preLoaderRoute: typeof HomePeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  BalanceRoute: BalanceRoute,
  HomePeriodRoute: HomePeriodRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
