version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cash-flow-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cashflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cash-flow-api
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./server/browser_data:/usr/src/app/browser_data
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/cashflow
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cash-flow-frontend
    ports:
      - "5173-5174:5173-5174"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pgdata:
